[project]
name = "qos-01"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.8.0",
    "jupyter-bokeh>=4.0.5",
    "jupyterlab>=4.4.7",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "panel>=1.8.0",
]
