textcolor = '#292929'
rc_params = {
    'legend.frameon': False,
    'legend.numpoints': 1,
    'legend.scatterpoints': 1,
    'xtick.direction': 'out',
    'ytick.direction': 'out',
    'axes.axisbelow': True,
    'axes.grid': True,
    'grid.linestyle': '--',
    'grid.linewidth': 1.3,
    'grid.color': '#e5e5e5',
    'font.family': 'sans-serif',
    'font.sans-serif': ['Roboto Condensed', 'Arial', 'Liberation Sans', 'DejaVu Sans', 'Bitstream Vera Sans', 'sans-serif'],
    'lines.solid_capstyle': 'round',
    'axes.linewidth': 0,
    'xtick.major.size': 0,
    'ytick.major.size': 0,
    'xtick.minor.size': 0,
    'ytick.minor.size': 0,
    'text.color': 'black',
    'axes.titlesize': 26,
    'axes.titlelocation': 'left',
    'axes.titleweight': 'bold',
    'axes.titlepad': 20,
    'axes.labelpad': 8,
    'axes.labelsize': 17,
    'axes.labelweight': 'bold',
    'xaxis.labellocation': 'right',
    'yaxis.labellocation': 'top',
    'ytick.labelsize': 15,
    'xtick.labelsize': 15,
    'legend.loc': 'center right',
    'legend.title_fontsize': 15,
    'legend.fontsize': 15,
    'legend.markerscale': 1.3,
    'figure.facecolor': '#ffffff',
    'axes.facecolor': '#ffffff',
    'savefig.facecolor': '#ffffff',
    'text.color': textcolor,
    'axes.labelcolor': textcolor,
    'xtick.color': textcolor,
    'ytick.color': textcolor,
}

colors = [
    "#00A499",
    "#43B02A",
    "#E4002B",
    "#FFB81C",
    "#0047BB",
    "#05C3DE",
    "#8246AF",
    "#FF8200",
]

