[project]
name = "qos-02"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.7",
    "loguru>=0.7.3",
    "matplotlib>=3.10.6",
    "networkx>=3.5",
    "simpy>=4.1.1",
]
