<!--
  Live PSNR / SSIM explorer: six distortions of one image, all scaled to the same MSE.

  A slider sets the target MSE. Each distortion is a fixed pattern Δ added to the reference with the weight
  that gives exactly that MSE, ref + αΔ, then clips to 0…255; where clipping costs more than 3 % of the
  MSE the row is marked "clipped". PSNR is therefore the same for every row; SSIM is not. Click a row to
  show that image, its SSIM map (white = identical structure, black = none) and an explanation of why SSIM
  reacts as it does — written for students going through the slide on their own.

  src   grayscale image under public/ (default '/images/06/explorer.png', 192 x 192, generated by
        scripts/generate-video-samples.py from the SVT old_town_cross sequence)

  SSIM follows Wang et al. (2004): 11 x 11 Gaussian window, σ = 1.5, K1 = 0.01, K2 = 0.03, L = 255, mean of
  the map over the valid (unpadded) region. Blur and blocking are capped at their full strength (α ≤ 1);
  beyond that the row shows the strongest version and its lower MSE.

  Interactive in the browser (`npm run dev`, the built site). In the PDF export (Slidev print mode) it draws
  a static layout instead: all six distortions at the default MSE, their SSIM maps and one line each.
-->
<script setup lang="ts">
import { computed, onMounted, ref, shallowRef, watch } from 'vue'
import { useNav } from '@slidev/client'

const props = withDefaults(defineProps<{ src?: string }>(), { src: '/images/06/explorer.png' })

type Kind = 'shift' | 'contrast' | 'noise' | 'impulse' | 'blur' | 'blocking'
const KINDS: { kind: Kind, label: string, capped: boolean }[] = [
  { kind: 'shift', label: 'Mean shift', capped: false },
  { kind: 'contrast', label: 'Contrast reduction', capped: false },
  { kind: 'noise', label: 'Gaussian noise', capped: false },
  { kind: 'impulse', label: 'Impulse noise (2 %)', capped: false },
  { kind: 'blur', label: 'Blur', capped: true },
  { kind: 'blocking', label: 'Blocking 8 × 8', capped: true },
]

// What each distortion does to the pixels, and why SSIM reacts the way it does — for students reading alone
const EXPLAIN: Record<Kind, { what: string, why: string, map: string, short: string }> = {
  shift: {
    what: 'Every pixel is made brighter by the same amount (√MSE grey levels).',
    why: 'Only the local mean changes. SSIM\'s luminance term compares the two means relative to their size, '
      + 'so even a shift of 14 levels (MSE 200) on a mid-grey picture costs very little; contrast and structure '
      + 'are untouched. '
      + 'The eye, which adapts to brightness, hardly notices either.',
    map: 'almost uniformly white.',
    short: 'Only the mean changes; contrast and structure are intact.',
  },
  contrast: {
    what: 'Every pixel is pulled towards the average brightness of the picture — the image looks flatter.',
    why: 'Edges and textures are all still there, just weaker: the structure term (correlation) stays at 1 and '
      + 'only the contrast term drops. Same situation as the worked example on the previous slide.',
    map: 'nearly white; only a faint outline of the strongest edges.',
    short: 'Edges are weaker but all still there — only the contrast term drops.',
  },
  noise: {
    what: 'An independent random value is added to every pixel.',
    why: 'Noise adds new, random structure everywhere. Where the picture has little structure of its own — the '
      + 'flat sky — the noise dominates each window and the correlation with the reference collapses. In the '
      + 'busy city, the original texture masks it, as it does for the eye.',
    map: 'darkest in the sky, lighter over the buildings.',
    short: 'New random structure everywhere; worst in the flat sky, masked in the busy city.',
  },
  impulse: {
    what: '2 % of the pixels, chosen at random, are pushed towards pure black or white; the rest are untouched.',
    why: 'The error budget is spent on a few large hits. Each disturbs the 11 × 11 windows around it, but the '
      + 'pixels between hits are exact — so SSIM falls less than for dense noise of the same MSE (Lab 04).',
    map: 'dark blotches, one 11 × 11 patch around every hit; white only in the gaps between them.',
    short: 'A few large hits; every pixel between them is exact.',
  },
  blur: {
    what: 'Each pixel is replaced by a weighted average of its neighbourhood (Gaussian blur).',
    why: 'Blur removes exactly what the structure term measures — edges and fine texture. Flat regions have '
      + 'nothing to lose, so they stay similar.',
    map: 'dark along the spire, the roofs and every edge; white in the sky.',
    short: 'Edges and fine texture removed; the flat sky has nothing to lose.',
  },
  blocking: {
    what: 'Each 8 × 8 block is replaced by its average — the extreme case of coarse quantisation in a codec.',
    why: 'Texture inside each block disappears and false edges appear at the block borders. Both destroy '
      + 'structure in detailed areas; flat blocks of sky are almost unchanged.',
    map: 'dark over the detailed city, white in the sky.',
    short: 'Texture inside each block lost, false edges added at block borders.',
  },
}

const target = ref(200)
const selected = ref<Kind>('blur')
const ready = ref(false)
const refImg = shallowRef<Float64Array>(new Float64Array())
const deltas = shallowRef<Record<Kind, Float64Array>>({} as Record<Kind, Float64Array>)
let W = 0
let H = 0

const distCanvas = ref<HTMLCanvasElement | null>(null)
const mapCanvas = ref<HTMLCanvasElement | null>(null)
const refCanvas = ref<HTMLCanvasElement | null>(null)

// --- image helpers ----------------------------------------------------------------
function rng(seed: number) {
  let s = seed >>> 0
  return () => ((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296)
}

function gaussian1d(sigma: number, radius: number) {
  const k = Array.from({ length: 2 * radius + 1 }, (_, i) => Math.exp(-((i - radius) ** 2) / (2 * sigma * sigma)))
  const sum = k.reduce((a, b) => a + b, 0)
  return k.map(v => v / sum)
}

// separable convolution with edge replication (used for blur, where the whole image is needed)
function convolveSame(img: Float64Array, k: number[]) {
  const r = (k.length - 1) / 2
  const tmp = new Float64Array(W * H)
  const out = new Float64Array(W * H)
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      let s = 0
      for (let i = -r; i <= r; i++) s += k[i + r] * img[y * W + Math.min(W - 1, Math.max(0, x + i))]
      tmp[y * W + x] = s
    }
  }
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      let s = 0
      for (let i = -r; i <= r; i++) s += k[i + r] * tmp[Math.min(H - 1, Math.max(0, y + i)) * W + x]
      out[y * W + x] = s
    }
  }
  return out
}

// separable convolution, valid region only: (W - 10) x (H - 10) for the 11-tap SSIM window
const WIN = gaussian1d(1.5, 5)
function filterValid(img: Float64Array) {
  const r = 5
  const w2 = W - 2 * r
  const h2 = H - 2 * r
  const tmp = new Float64Array(w2 * H)
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < w2; x++) {
      let s = 0
      for (let i = 0; i <= 2 * r; i++) s += WIN[i] * img[y * W + x + i]
      tmp[y * w2 + x] = s
    }
  }
  const out = new Float64Array(w2 * h2)
  for (let y = 0; y < h2; y++) {
    for (let x = 0; x < w2; x++) {
      let s = 0
      for (let i = 0; i <= 2 * r; i++) s += WIN[i] * tmp[(y + i) * w2 + x]
      out[y * w2 + x] = s
    }
  }
  return out
}

function ssimMap(a: Float64Array, b: Float64Array) {
  const C1 = (0.01 * 255) ** 2
  const C2 = (0.03 * 255) ** 2
  const n = W * H
  const aa = new Float64Array(n)
  const bb = new Float64Array(n)
  const ab = new Float64Array(n)
  for (let i = 0; i < n; i++) {
    aa[i] = a[i] * a[i]
    bb[i] = b[i] * b[i]
    ab[i] = a[i] * b[i]
  }
  const ma = filterValid(a)
  const mb = filterValid(b)
  const saa = filterValid(aa)
  const sbb = filterValid(bb)
  const sab = filterValid(ab)
  const map = new Float64Array(ma.length)
  let sum = 0
  for (let i = 0; i < map.length; i++) {
    const va = saa[i] - ma[i] * ma[i]
    const vb = sbb[i] - mb[i] * mb[i]
    const cov = sab[i] - ma[i] * mb[i]
    map[i] = ((2 * ma[i] * mb[i] + C1) * (2 * cov + C2)) / ((ma[i] ** 2 + mb[i] ** 2 + C1) * (va + vb + C2))
    sum += map[i]
  }
  return { map, mean: sum / map.length }
}

function buildDeltas(img: Float64Array) {
  const n = W * H
  const mean = img.reduce((a, b) => a + b, 0) / n
  const random = rng(6)
  const d = {} as Record<Kind, Float64Array>
  d.shift = new Float64Array(n).fill(1)
  d.contrast = img.map(v => mean - v)
  d.noise = new Float64Array(n).map(() => {
    const u = Math.max(random(), 1e-12)
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * random())
  })
  d.impulse = new Float64Array(n).map((_, i) => (random() < 0.02 ? (random() < 0.5 ? 0 : 255) - img[i] : 0))
  d.blur = convolveSame(img, gaussian1d(3, 9)).map((v, i) => v - img[i])
  d.blocking = new Float64Array(n)
  for (let by = 0; by < H; by += 8) {
    for (let bx = 0; bx < W; bx += 8) {
      let s = 0
      let c = 0
      for (let y = by; y < Math.min(H, by + 8); y++) for (let x = bx; x < Math.min(W, bx + 8); x++) { s += img[y * W + x]; c++ }
      for (let y = by; y < Math.min(H, by + 8); y++) for (let x = bx; x < Math.min(W, bx + 8); x++) d.blocking[y * W + x] = s / c - img[y * W + x]
    }
  }
  return d
}

// --- the six results at the current target MSE -------------------------------------
interface Row { kind: Kind, label: string, img: Float64Array, mse: number, psnr: number, ssim: number, map: Float64Array, capped: boolean, clipped: boolean, alpha: number }

const rows = computed<Row[]>(() => {
  if (!ready.value) return []
  const img = refImg.value
  return KINDS.map(({ kind, label, capped }) => {
    const d = deltas.value[kind]
    const energy = d.reduce((s, v) => s + v * v, 0) / d.length
    let alpha = Math.sqrt(target.value / energy)
    const hitCap = capped && alpha > 1
    if (hitCap) alpha = 1
    const out = img.map((v, i) => Math.min(255, Math.max(0, v + alpha * d[i])))
    const mse = out.reduce((s, v, i) => s + (v - img[i]) ** 2, 0) / out.length
    const { map, mean } = ssimMap(img, out)
    const clipped = !hitCap && mse < 0.97 * target.value  // pixels pushed past 0 or 255 lose part of the error
    return { kind, label, img: out, mse, psnr: 10 * Math.log10(255 * 255 / mse), ssim: mean, map, capped: hitCap, clipped, alpha }
  })
})
const current = computed(() => rows.value.find(r => r.kind === selected.value))

// PDF export: no interaction, so show all six distortions at the default MSE side by side instead
const { isPrintMode } = useNav()
function printCanvas(el: unknown, data: Float64Array, w: number, h: number, scale = 1) {
  if (el instanceof HTMLCanvasElement) paint(el, data, w, h, scale)
}

// How strong the selected distortion has to be to produce the target MSE (α scales its fixed pattern Δ)
const strength = computed(() => {
  const r = current.value
  if (!r) return ''
  const a = r.alpha
  const pct = `${Math.round(a * 100)} %`
  switch (r.kind) {
    case 'shift': return `every pixel +${a.toFixed(1)} grey levels`
    case 'contrast': return `every pixel moved ${pct} of the way to the mean brightness`
    case 'noise': return `noise with standard deviation σ = ${a.toFixed(1)} grey levels`
    case 'impulse': return a >= 1 ? 'hits at full black or white' : `hits pushed ${pct} of the way to black or white`
    case 'blur': return `${pct} of a Gaussian blur with σ = 3 px`
    case 'blocking': return `${pct} of the way to flat 8 × 8 block averages`
  }
})

function paint(canvas: HTMLCanvasElement | null, data: Float64Array, w: number, h: number, scale = 1) {
  if (!canvas) return
  canvas.width = w
  canvas.height = h
  const ctx = canvas.getContext('2d')!
  const px = ctx.createImageData(w, h)
  for (let i = 0; i < w * h; i++) {
    const v = Math.round(Math.min(255, Math.max(0, data[i] * scale)))
    px.data.set([v, v, v, 255], 4 * i)
  }
  ctx.putImageData(px, 0, 0)
}

watch([current, ready], () => {
  if (!current.value) return
  paint(refCanvas.value, refImg.value, W, H)
  paint(distCanvas.value, current.value.img, W, H)
  // SSIM map: 1 → white, 0 or below → black
  paint(mapCanvas.value, current.value.map.map(v => Math.max(0, v)), W - 10, H - 10, 255)
}, { flush: 'post' })

onMounted(() => {
  const im = new Image()
  im.onload = () => {
    W = im.naturalWidth
    H = im.naturalHeight
    const c = document.createElement('canvas')
    c.width = W
    c.height = H
    const ctx = c.getContext('2d')!
    ctx.drawImage(im, 0, 0)
    const rgba = ctx.getImageData(0, 0, W, H).data
    const img = new Float64Array(W * H).map((_, i) => rgba[4 * i])
    refImg.value = img
    deltas.value = buildDeltas(img)
    ready.value = true
  }
  im.src = props.src
})
</script>

<template>
  <div v-if="isPrintMode" class="quality-explorer-print">
    <div class="strip">
      <figure>
        <canvas :ref="el => ready && printCanvas(el, refImg, W, H)" />
        <figcaption><b>Reference</b></figcaption>
        <div class="maps-label">SSIM map ↓<br>white = same structure<br>black = none</div>
      </figure>
      <figure v-for="r in rows" :key="r.kind">
        <canvas :ref="el => printCanvas(el, r.img, W, H)" />
        <figcaption><b>{{ r.label }}</b><br>SSIM <b>{{ r.ssim.toFixed(2) }}</b></figcaption>
        <canvas class="map" :ref="el => printCanvas(el, r.map.map(v => Math.max(0, v)), W - 10, H - 10, 255)" />
      </figure>
    </div>
    <p class="lead">All six distortions are scaled to the <b>same MSE = {{ target }}</b>, so PSNR is identical for every one
      ({{ (10 * Math.log10(255 * 255 / target)).toFixed(1) }} dB). SSIM compares mean, contrast and structure in an
      11 × 11 window around every pixel and ranks them very differently:</p>
    <ul class="why">
      <li v-for="r in rows" :key="r.kind"><b>{{ r.label }} ({{ r.ssim.toFixed(2) }}):</b> {{ EXPLAIN[r.kind].short }}</li>
    </ul>
  </div>
  <div v-else class="quality-explorer">
    <div class="panels">
      <figure>
        <canvas ref="refCanvas" />
        <figcaption>Reference</figcaption>
      </figure>
      <figure>
        <canvas ref="distCanvas" />
        <figcaption>{{ current?.label ?? '…' }}</figcaption>
      </figure>
      <figure>
        <canvas ref="mapCanvas" class="map" />
        <figcaption>SSIM map · white = same structure, black = none</figcaption>
      </figure>
    </div>

    <div class="howto">
      <label class="slider">
        MSE (all rows)
        <input v-model.number="target" type="range" min="10" max="600" step="10">
        <span class="num">{{ target }} → PSNR {{ (10 * Math.log10(255 * 255 / target)).toFixed(1) }} dB</span>
      </label>
      <p><b>How it works.</b> The slider sets one MSE for <b>all six rows</b>: each distortion is made just strong
        enough to reach it, so <b>PSNR is the same in every row</b>. Clicking a row only chooses what is shown.</p>
      <p>SSIM compares mean, contrast and structure in an 11 × 11 window around every pixel; the <b>SSIM map</b>
        shows each window, the table their average.</p>
    </div>

    <table>
      <colgroup><col style="width: 235px"><col style="width: 55px"><col style="width: 60px"><col></colgroup>
      <thead><tr><th>Distortion</th><th>MSE</th><th>PSNR</th><th>SSIM</th></tr></thead>
      <tbody>
        <tr v-for="r in rows" :key="r.kind" :class="{ on: r.kind === selected }" @click="selected = r.kind">
          <td>{{ r.label }}<span v-if="r.capped" class="cap"> max</span><span v-else-if="r.clipped" class="cap"> clipped</span></td>
          <td class="num">{{ r.mse.toFixed(0) }}</td>
          <td class="num">{{ r.psnr.toFixed(1) }}</td>
          <td class="ssim">
            <span class="bar" :style="{ width: `${Math.max(0, r.ssim) * 70}px` }" />
            <span class="num">{{ r.ssim.toFixed(2) }}</span>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="explain">
      <div class="head">{{ current?.label }} · SSIM {{ current?.ssim.toFixed(2) }}</div>
      <p><b>Strength at this MSE:</b> {{ strength }}.</p>
      <p><b>What changes:</b> {{ EXPLAIN[selected].what }}</p>
      <p><b>Why SSIM reacts this way:</b> {{ EXPLAIN[selected].why }}</p>
      <p><b>SSIM map:</b> {{ EXPLAIN[selected].map }}</p>
      <p v-if="current?.capped" class="try"><b>max</b>: full strength reached, the real MSE stays below the target.</p>
      <p v-else-if="current?.clipped" class="try"><b>clipped</b>: pixels hit black or white, so the real MSE stays below the target.</p>
    </div>
  </div>
</template>

<style scoped>
.quality-explorer-print { margin-top: 0.2rem; font-size: 14px; line-height: 1.35; color: var(--vsb-ink); }
.strip { display: grid; grid-template-columns: repeat(7, 112px); gap: 10px; }
.strip canvas { width: 112px; height: 112px; }
.strip canvas.map { width: 112px; height: 106px; margin-top: 4px; }
.strip figcaption { font-size: 12px; min-height: 30px; }
.maps-label { margin-top: 4px; height: 106px; display: flex; align-items: center; font-size: 12px; line-height: 1.3; color: var(--vsb-muted); }
.lead { margin: 0.5rem 0 0.3rem !important; font-size: 14px !important; line-height: 1.4 !important; }
.why { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 24px; margin: 0 !important; padding-left: 1.1em; font-size: 13.5px; }
.why li { margin: 0 !important; line-height: 1.35; }
.quality-explorer {
  display: grid;
  grid-template-columns: 470px 1fr;
  grid-template-rows: auto auto;
  gap: 10px 20px;
  margin-top: 0.2rem;
  font-size: 14px;
  line-height: 1.35;
  color: var(--vsb-ink);
}
.panels { display: grid; grid-template-columns: repeat(3, 150px); gap: 10px; }
figure { margin: 0; }
canvas { display: block; width: 150px; height: 150px; image-rendering: pixelated; border: 1px solid var(--vsb-hairline); }
canvas.map { width: 150px; height: 142px; }
figcaption { font-size: 12px; line-height: 1.2; color: var(--vsb-muted); margin-top: 3px; }
.howto p, .explain p { margin: 0 0 0.35rem !important; font-size: 13.5px !important; line-height: 1.35 !important; }
.howto .try { color: var(--vsb-muted); }
.slider { display: flex; align-items: center; gap: 0.5em; margin-bottom: 0.35rem; font-size: 14px; white-space: nowrap; }
.slider input { width: 130px; accent-color: var(--vsb-green); }
table { width: 470px; table-layout: fixed; border-collapse: collapse; align-self: start; }  /* fixed: the max/clipped flags must not resize columns */
th { text-align: left; font-weight: 700; color: var(--vsb-green-text); border-bottom: 2px solid var(--vsb-green); padding: 2px 6px; }
td { padding: 3px 6px; white-space: nowrap; border-bottom: 1px solid var(--vsb-hairline); cursor: pointer; }
tr.on td { background: var(--vsb-hairline); font-weight: 700; }
.num { font-variant-numeric: tabular-nums; }
.ssim { white-space: nowrap; }
.bar { display: inline-block; height: 10px; margin-right: 6px; background: var(--vsb-green); vertical-align: middle; }
.cap { font-size: 12px; color: var(--vsb-muted); font-weight: 400; }
.explain { border-left: 4px solid var(--vsb-green); padding: 2px 0 2px 12px; align-self: start; }
.explain .head { font-weight: 700; color: var(--vsb-green-text); margin-bottom: 0.25rem; }
</style>
