<!--
  A short, silent, looping video sample with a caption, for side-by-side comparisons of impairments.

  src      path of the clip under public/, e.g. '/video/06/packet-loss.mp4'
  poster   still shown before playback and in the PDF export, e.g. '/video/06/packet-loss.jpg'
  caption  text under the clip
  width    display width in slide px (default 280); the clips are 16:9

  Click the clip to play or pause it; starting one clip pauses any other, as AudioClip does for sound.
  Hard-edged, green frame while playing (VSB-STYLE.md R6, R24). The PDF export shows the poster.
  Clips and posters are generated by scripts/generate-video-samples.py.
-->
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import { onSlideLeave } from '@slidev/client'

const props = withDefaults(defineProps<{ src: string, poster: string, caption?: string, width?: number }>(),
  { width: 280 })
const video = ref<HTMLVideoElement | null>(null)
const playing = ref(false)

function pause() {
  video.value?.pause()
  playing.value = false
}

function onOtherPlay(event: Event) {
  if ((event as CustomEvent<HTMLVideoElement>).detail !== video.value) pause()
}

function toggle() {
  const el = video.value
  if (!el) return
  if (playing.value) return pause()
  window.dispatchEvent(new CustomEvent('video-clip-play', { detail: el }))
  el.play()
  playing.value = true
}

window.addEventListener('video-clip-play', onOtherPlay)
onSlideLeave(pause)
onBeforeUnmount(() => {
  window.removeEventListener('video-clip-play', onOtherPlay)
  pause()
})
</script>

<template>
  <figure class="video-clip" :style="{ width: `${props.width}px` }">
    <button type="button" class="frame" :class="{ playing }" :aria-label="`${playing ? 'Pause' : 'Play'} ${caption ?? 'clip'}`"
            @click.stop="toggle">
      <video ref="video" :src="src" :poster="poster" muted loop playsinline preload="metadata" />
      <span v-if="!playing" class="badge" aria-hidden="true">▶</span>
    </button>
    <figcaption v-if="caption">{{ caption }}</figcaption>
  </figure>
</template>

<style scoped>
.video-clip { margin: 0; }
.frame {
  position: relative;
  display: block;
  width: 100%;
  padding: 0;
  border: 2px solid var(--vsb-hairline);
  border-radius: 0;
  background: #000000;
  cursor: pointer;
}
.frame.playing { border-color: var(--vsb-green); }
video { display: block; width: 100%; aspect-ratio: 16 / 9; object-fit: cover; }
.badge {
  position: absolute;
  left: 8px;
  bottom: 8px;
  padding: 0.05em 0.45em;
  background: #005F58;  /* white on the darkened green: 7.56:1 (R5) */
  color: #FFFFFF;
  font-size: 14px;
  line-height: 1.4;
}
figcaption { margin-top: 0.3rem; font-size: 15px; line-height: 1.3; color: var(--vsb-muted); }
</style>
